# fly.toml - Fly.io configuration for SIP Gateway

app = "trunk-talk-dialer"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8080"

[[services]]
auto_start_machines = true
auto_stop_machines = true
internal_port = 8_080
min_machines_running = 0
protocol = "tcp"

  [[services.http_checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  path = "/health"
  timeout = "5s"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "http", "tls" ]
  port = 443
